[pytest]
addopts =
    --html=reports/report.html
    --self-contained-html
    --json-report
    --json-report-file=reports/report.json
    -v

testpaths = tests

markers =
    smoke: Smoke test suite
    regression: Regression test suite
    login: Login related tests
    api: API tests
